import { Activity, BarChart3, CheckCircle2, Loader2, Users } from "lucide-react";

const shortDay=value=>new Intl.DateTimeFormat("en-NG",{weekday:"short",day:"numeric"}).format(new Date(value));
const Empty=({text})=><div className="grid h-52 place-items-center text-center text-sm text-slate-400">{text}</div>;
const Loading=()=> <div className="grid h-52 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-purple-500" aria-label="Loading analytics"/></div>;

function ActivityTrend({data}){
 const max=Math.max(1,...data.flatMap(item=>[Number(item.attempts),Number(item.registrations)]));
 return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-2"><header className="flex items-start justify-between gap-4"><div><h3 className="flex items-center gap-2 text-lg font-black text-slate-900"><Activity size={20} className="text-purple-600"/>14-day activity</h3><p className="mt-1 text-sm text-slate-500">Game attempts and new player registrations by day.</p></div><div className="flex flex-wrap justify-end gap-3 text-xs font-bold text-slate-500"><span className="flex items-center gap-1"><i className="h-2.5 w-2.5 rounded-full bg-purple-500"/>Attempts</span><span className="flex items-center gap-1"><i className="h-2.5 w-2.5 rounded-full bg-pink-400"/>Registrations</span></div></header>
 <div className="mt-6 flex h-52 items-end gap-1.5 sm:gap-3">{data.map(item=><div key={item.day} className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2" title={`${shortDay(item.day)}: ${item.attempts} attempts, ${item.registrations} registrations, ${item.active_players} active players`}><div className="flex h-40 w-full items-end justify-center gap-0.5 sm:gap-1"><span className="w-2/5 min-w-1 rounded-t-md bg-gradient-to-t from-purple-600 to-purple-400 transition-opacity group-hover:opacity-75" style={{height:`${Math.max(Number(item.attempts)?4:0,Number(item.attempts)*100/max)}%`}}/><span className="w-2/5 min-w-1 rounded-t-md bg-gradient-to-t from-pink-500 to-pink-300 transition-opacity group-hover:opacity-75" style={{height:`${Math.max(Number(item.registrations)?4:0,Number(item.registrations)*100/max)}%`}}/></div><span className="hidden truncate text-[10px] text-slate-400 min-[520px]:block">{shortDay(item.day)}</span></div>)}</div></article>;
}

function OutcomeChart({data}){
 const total=Number(data.total||0),passed=Number(data.passed||0),failed=Number(data.failed||0),rate=total?Math.round(passed*100/total):0;
 return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="flex items-center gap-2 text-lg font-black"><CheckCircle2 size={20} className="text-emerald-500"/>Gameplay outcomes</h3><p className="mt-1 text-sm text-slate-500">Pass performance during the last 30 days.</p>{total?<div className="mt-6 flex flex-col items-center"><div className="grid h-40 w-40 place-items-center rounded-full" style={{background:`conic-gradient(#10b981 0 ${rate}%,#fda4af ${rate}% 100%)`}}><div className="grid h-28 w-28 place-items-center rounded-full bg-white text-center shadow-inner"><div><p className="text-3xl font-black text-slate-900">{rate}%</p><p className="text-xs font-bold text-slate-400">pass rate</p></div></div></div><div className="mt-5 grid w-full grid-cols-3 gap-2 text-center"><div><p className="text-xl font-black">{total}</p><p className="text-xs text-slate-400">Attempts</p></div><div><p className="text-xl font-black text-emerald-600">{passed}</p><p className="text-xs text-slate-400">Passed</p></div><div><p className="text-xl font-black text-rose-500">{failed}</p><p className="text-xs text-slate-400">Not passed</p></div></div><p className="mt-4 rounded-full bg-purple-50 px-3 py-1 text-xs font-bold text-purple-700">{Number(data.average_score)}% average score</p></div>:<Empty text="No gameplay recorded in the last 30 days."/>}</article>;
}

function CategoryChart({data}){
 const max=Math.max(1,...data.map(item=>Number(item.attempts)));
 return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-3"><header><h3 className="flex items-center gap-2 text-lg font-black"><BarChart3 size={20} className="text-indigo-600"/>Most-played categories</h3><p className="mt-1 text-sm text-slate-500">Engagement and performance by learning category over the last 30 days.</p></header>{data.length?<div className="mt-6 space-y-5">{data.map((item,index)=><div key={item.id} className="grid gap-2 sm:grid-cols-[minmax(130px,220px)_1fr_220px] sm:items-center"><div className="min-w-0"><p className="truncate font-bold text-slate-800">{item.name}</p><p className="text-xs text-slate-400">{item.players} player{Number(item.players)===1?"":"s"}</p></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${["bg-purple-500","bg-indigo-500","bg-pink-500","bg-amber-500","bg-emerald-500"][index%5]}`} style={{width:`${Number(item.attempts)*100/max}%`}}/></div><div className="flex justify-between gap-3 text-xs"><span><b className="text-slate-900">{item.attempts}</b> attempts</span><span><b className="text-slate-900">{item.pass_rate}%</b> pass rate</span><span><b className="text-slate-900">{item.average_score}%</b> avg</span></div></div>)}</div>:<Empty text="Category analytics will appear after players start games."/>}</article>;
}

export default function DashboardAnalytics({analytics,loading}){
 return <section className="pb-8"><div className="mb-4"><h2 className="flex items-center gap-2 text-xl font-black text-slate-900"><Users size={22} className="text-purple-600"/>Activity insights</h2><p className="mt-1 text-sm text-slate-500">A quick view of engagement and learning performance.</p></div><div className="grid gap-6 lg:grid-cols-3">{loading?<><article className="rounded-2xl border bg-white lg:col-span-2"><Loading/></article><article className="rounded-2xl border bg-white"><Loading/></article><article className="rounded-2xl border bg-white lg:col-span-3"><Loading/></article></>:<><ActivityTrend data={analytics?.dailyActivity||[]}/><OutcomeChart data={analytics?.gameplayOutcomes||{}}/><CategoryChart data={analytics?.categoryPerformance||[]}/></>}</div></section>;
}
