import { Link } from "react-router-dom";

const relativeTime=value=>{const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return"Just now";if(seconds<3600)return`${Math.floor(seconds/60)} mins ago`;if(seconds<86400)return`${Math.floor(seconds/3600)} hours ago`;return`${Math.floor(seconds/86400)} days ago`};
export default function RecentTransactions({data=[],loading=false}){
 return <div className="bg-white p-5 rounded-xl shadow-sm border"><div className="flex justify-between items-center mb-4"><h2 className="text-lg font-semibold">Recent Coin Transactions</h2><Link to="/coin-system" className="text-purple-600 text-sm">View All</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="text-gray-500 border-b"><tr><th className="py-2 text-left">User</th><th className="py-2 text-left">Type</th><th className="py-2 text-left">Amount</th><th className="py-2 text-left">Status</th><th className="py-2 text-left">Date</th></tr></thead><tbody>
 {data.map(tx=><tr key={tx.id} className="border-b last:border-none"><td className="py-3 flex items-center gap-3"><span className="grid w-8 h-8 shrink-0 place-items-center rounded-full bg-purple-100 font-bold text-purple-700">{tx.user_name?.[0]?.toUpperCase()||"?"}</span>{tx.user_name}</td><td><span className={`px-3 py-1 rounded-full text-xs capitalize ${tx.type==="purchase"?"bg-green-100 text-green-600":"bg-yellow-100 text-yellow-600"}`}>{tx.type}</span></td><td>{Math.abs(Number(tx.amount)).toLocaleString()} Coins</td><td><span className="px-3 py-1 rounded-full text-xs bg-green-100 text-green-600">Completed</span></td><td>{relativeTime(tx.created_at)}</td></tr>)}
 {!data.length&&<tr><td colSpan="5" className="py-12 text-center text-slate-400">{loading?"Loading transactions...":"No transactions yet."}</td></tr>}
 </tbody></table></div></div>;
}
