import { useCallback, useEffect, useState } from "react";
import axios from "axios";
import { Award, RefreshCw, Search, Trophy, Users } from "lucide-react";
import { toast } from "react-toastify";

const periods=[{id:"all",label:"All time"},{id:"month",label:"Last 30 days"},{id:"week",label:"Last 7 days"}];
const rankStyle=rank=>rank===1?"bg-amber-100 text-amber-700":rank===2?"bg-slate-200 text-slate-700":rank===3?"bg-orange-100 text-orange-700":"bg-purple-50 text-purple-700";
export default function Leaderboard(){
 const[players,setPlayers]=useState([]),[pagination,setPagination]=useState({page:1,limit:20,total:0}),[period,setPeriod]=useState("all"),[search,setSearch]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const{data}=await axios.get(`/admin/leaderboard?period=${period}&page=${pagination.page}&limit=${pagination.limit}&search=${encodeURIComponent(search)}`);setPlayers(data.players||[]);setPagination(p=>({...p,...data.pagination}))}catch(e){toast.error(e.response?.data?.message||"Unable to load leaderboard.")}finally{setLoading(false)}},[period,pagination.page,pagination.limit,search]);
 useEffect(()=>{const timer=setTimeout(load,search?300:0);return()=>clearTimeout(timer)},[load,search]);
 const top=players[0];
 return <div className="min-h-screen bg-slate-50 p-4 sm:p-7"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-black text-slate-900"><Trophy className="text-amber-500"/>Leaderboard</h1><p className="mt-1 text-sm text-slate-500">Verified rankings based on best-level performance and earned XP.</p></div><button onClick={load} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-2 text-sm font-bold"><RefreshCw size={16}/>Refresh</button></header>
 <div className="mb-5 grid gap-4 sm:grid-cols-3"><Stat icon={<Users/>} label="Ranked players" value={pagination.total}/><Stat icon={<Award/>} label="Current leader" value={top?.name||"—"}/><Stat icon={<Trophy/>} label="Leading XP" value={top?Number(period==="all"?top.total_xp:top.period_xp).toLocaleString():"0"}/></div>
 <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div className="relative min-w-64 flex-1 max-w-md"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={e=>{setSearch(e.target.value);setPagination(p=>({...p,page:1}))}} placeholder="Search player or username" className="w-full rounded-xl border py-2.5 pl-10 pr-3 outline-none focus:border-purple-500"/></div><div className="flex rounded-xl bg-slate-100 p-1">{periods.map(p=><button key={p.id} onClick={()=>{setPeriod(p.id);setPagination(x=>({...x,page:1}))}} className={`rounded-lg px-3 py-2 text-sm font-bold ${period===p.id?"bg-white text-purple-700 shadow-sm":"text-slate-500"}`}>{p.label}</button>)}</div></div>
 {loading?<div className="py-24 text-center text-slate-400">Loading rankings…</div>:players.length?<div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Rank</th><th className="p-4">Player</th><th className="p-4">XP</th><th className="p-4">Levels completed</th><th className="p-4">Average score</th><th className="p-4">Attempts</th><th className="p-4">Coins</th><th className="p-4">Lives</th><th className="p-4">Last played</th></tr></thead><tbody>{players.map(player=><tr key={player.id} className="border-t hover:bg-purple-50/30"><td className="p-4"><span className={`inline-grid h-9 w-9 place-items-center rounded-full font-black ${rankStyle(Number(player.rank))}`}>{player.rank}</span></td><td className="p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-purple-100 font-black text-purple-700">{player.name?.[0]?.toUpperCase()}</div><div><p className="font-bold text-slate-900">{player.name}</p><p className="text-xs text-slate-400">@{player.username}</p></div></div></td><td className="p-4 font-black text-purple-700">{Number(period==="all"?player.total_xp:player.period_xp).toLocaleString()}</td><td className="p-4">{player.completed_levels}</td><td className="p-4">{player.average_score}%</td><td className="p-4">{player.attempts}</td><td className="p-4">{Number(player.coins_count).toLocaleString()}</td><td className="p-4">{player.lives_remaining}</td><td className="p-4 text-slate-500">{player.last_played?new Date(player.last_played).toLocaleString():"Never"}</td></tr>)}</tbody></table></div>:<div className="py-24 text-center text-slate-400">No matching ranked players.</div>}
 <footer className="flex items-center justify-between border-t p-4 text-sm text-slate-500"><span>Showing {players.length?((pagination.page-1)*pagination.limit)+1:0}–{Math.min(pagination.page*pagination.limit,pagination.total)} of {pagination.total}</span><div className="flex gap-2"><button disabled={pagination.page<=1} onClick={()=>setPagination(p=>({...p,page:p.page-1}))} className="rounded-lg border px-3 py-2 disabled:opacity-40">Previous</button><button disabled={pagination.page*pagination.limit>=pagination.total} onClick={()=>setPagination(p=>({...p,page:p.page+1}))} className="rounded-lg border px-3 py-2 disabled:opacity-40">Next</button></div></footer></section></div></div>;
}
function Stat({icon,label,value}){return <div className="flex items-center gap-4 rounded-2xl border bg-white p-4 shadow-sm"><div className="grid h-11 w-11 place-items-center rounded-xl bg-purple-100 text-purple-700">{icon}</div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 truncate text-xl font-black text-slate-900">{value}</p></div></div>}
