import { useCallback, useEffect, useState } from "react";
import axios from "axios";
import { Award, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "react-toastify";

const blank={name:"",description:"",tier:"bronze",criteriaType:"levels_completed",criteriaValue:1,isActive:true,sortOrder:0};
const criteria={
 levels_completed:{label:"Different levels completed",help:"Awarded after the player passes this many different levels.",unit:"levels"},
 attempts_completed:{label:"Game attempts finished",help:"Awarded after the player submits this many completed game attempts.",unit:"attempts"},
 perfect_scores:{label:"Perfect scores achieved",help:"Awarded after the player scores 100% this many times.",unit:"perfect scores"},
 total_xp:{label:"Total XP earned",help:"Awarded when the player’s total XP reaches this number.",unit:"XP"},
};
const tierStyle={bronze:"bg-amber-100 text-amber-800",silver:"bg-slate-200 text-slate-700",gold:"bg-yellow-100 text-yellow-800",platinum:"bg-violet-100 text-violet-700"};
const input="mt-1 w-full rounded-xl border border-gray-300 px-4 py-3 text-sm outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-100";
const sentence=badge=>`${criteria[badge.criteria_type]?.label||badge.criteria_type}: ${Number(badge.criteria_value).toLocaleString()}`;

export default function BadgeSettings(){
 const[badges,setBadges]=useState([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState(null),[deleting,setDeleting]=useState(null),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const{data}=await axios.get("/admin/badges");setBadges(data.badges||[])}catch(e){toast.error(e.response?.data?.message||"Unable to load badges.")}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const open=badge=>setEditing(badge?{...badge,criteriaType:badge.criteria_type,criteriaValue:badge.criteria_value,isActive:badge.is_active,sortOrder:badge.sort_order}:blank);
 const save=async event=>{event.preventDefault();setSaving(true);const d=editing,payload={name:d.name.trim(),description:d.description.trim(),tier:d.tier,criteriaType:d.criteriaType,criteriaValue:Number(d.criteriaValue),isActive:Boolean(d.isActive),sortOrder:Number(d.sortOrder)||0};try{d.id?await axios.put(`/admin/badges/${d.id}`,payload):await axios.post("/admin/badges",payload);toast.success(`Badge ${d.id?"updated":"created"}.`);setEditing(null);load()}catch(e){toast.error(e.response?.data?.message||e.response?.data?.errors?.[0]?.message||"Unable to save badge.")}finally{setSaving(false)}};
 const remove=async()=>{setSaving(true);try{await axios.delete(`/admin/badges/${deleting.id}`);toast.success("Badge deleted.");setDeleting(null);load()}catch(e){toast.error(e.response?.data?.message||"Unable to delete badge.")}finally{setSaving(false)}};
 return <section className="p-6"><div className="max-w-6xl">
  <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-bold text-gray-900">Badge Settings</h2><p className="mt-1 max-w-3xl text-sm text-gray-500">Badges are awarded automatically to every player when their recorded progress reaches an active rule. Each player can earn a badge only once.</p></div><button onClick={()=>open(null)} className="flex items-center gap-2 rounded-xl bg-purple-600 px-5 py-3 text-sm font-bold text-white"><Plus size={17}/>Create badge</button></div>
  <div className="mb-6 rounded-xl border border-purple-100 bg-purple-50 p-4 text-sm text-purple-900"><b>How it works:</b> choose what progress to measure, enter the required number, and keep the badge active. Updates affect future eligibility checks for all users. Deleting a badge also removes that badge from users who earned it.</div>
  {loading?<div className="rounded-xl border bg-white py-20 text-center text-gray-400">Loading badges...</div>:badges.length?<div className="overflow-x-auto rounded-xl border border-[#DBDEE5] bg-white"><table className="w-full min-w-[850px] text-sm"><thead className="bg-gray-50"><tr><th className="px-5 py-4 text-left">Badge</th><th className="px-5 py-4 text-left">Tier</th><th className="px-5 py-4 text-left">Earning rule</th><th className="px-5 py-4 text-left">Earned</th><th className="px-5 py-4 text-left">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{badges.map(badge=><tr key={badge.id} className="border-t"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-purple-100 text-purple-600"><Award size={20}/></span><div><p className="font-bold text-gray-900">{badge.name}</p><p className="max-w-xs text-xs text-gray-500">{badge.description||"No description"}</p></div></div></td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${tierStyle[badge.tier]}`}>{badge.tier}</span></td><td className="px-5 py-4"><p className="font-semibold text-gray-800">{sentence(badge)}</p><p className="text-xs text-gray-400">{criteria[badge.criteria_type]?.help}</p></td><td className="px-5 py-4 font-bold">{Number(badge.earned_count).toLocaleString()}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${badge.is_active?"bg-green-100 text-green-700":"bg-gray-100 text-gray-500"}`}>{badge.is_active?"Active":"Paused"}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button aria-label={`Edit ${badge.name}`} onClick={()=>open(badge)} className="rounded-lg p-2 text-purple-600 hover:bg-purple-50"><Pencil size={17}/></button><button aria-label={`Delete ${badge.name}`} onClick={()=>setDeleting(badge)} className="rounded-lg p-2 text-red-500 hover:bg-red-50"><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></div>:<div className="rounded-xl border bg-white py-20 text-center text-gray-400">No badges exist yet. Create the first badge.</div>}
 </div>
 {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" onMouseDown={()=>setEditing(null)}><form onSubmit={save} onMouseDown={e=>e.stopPropagation()} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h3 className="text-xl font-bold">{editing.id?"Edit badge":"Create badge"}</h3><p className="text-sm text-gray-500">This rule applies equally to every player.</p></div><button type="button" onClick={()=>setEditing(null)} className="text-2xl text-gray-400">×</button></div><label className="mb-4 block text-sm font-semibold">Badge name<input required minLength="2" value={editing.name} onChange={e=>setEditing(x=>({...x,name:e.target.value}))} className={input}/></label><label className="mb-4 block text-sm font-semibold">Description<textarea rows="3" maxLength="500" value={editing.description} onChange={e=>setEditing(x=>({...x,description:e.target.value}))} className={input}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Tier<select value={editing.tier} onChange={e=>setEditing(x=>({...x,tier:e.target.value}))} className={input}>{["bronze","silver","gold","platinum"].map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></label><label className="text-sm font-semibold">Display order<input type="number" min="0" value={editing.sortOrder} onChange={e=>setEditing(x=>({...x,sortOrder:e.target.value}))} className={input}/></label></div><label className="mt-4 block text-sm font-semibold">Progress to measure<select value={editing.criteriaType} onChange={e=>setEditing(x=>({...x,criteriaType:e.target.value}))} className={input}>{Object.entries(criteria).map(([key,value])=><option key={key} value={key}>{value.label}</option>)}</select><span className="mt-1 block font-normal text-gray-500">{criteria[editing.criteriaType].help}</span></label><label className="mt-4 block text-sm font-semibold">Required number of {criteria[editing.criteriaType].unit}<input required type="number" min="1" max="10000000" value={editing.criteriaValue} onChange={e=>setEditing(x=>({...x,criteriaValue:e.target.value}))} className={input}/></label><label className="mt-5 flex items-center gap-3 rounded-xl bg-gray-50 p-4 text-sm"><input type="checkbox" checked={editing.isActive} onChange={e=>setEditing(x=>({...x,isActive:e.target.checked}))}/><span><b>Active badge</b><span className="block text-xs text-gray-500">Players can earn this badge when enabled.</span></span></label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setEditing(null)} className="rounded-xl border px-5 py-2.5">Cancel</button><button disabled={saving} className="rounded-xl bg-purple-600 px-5 py-2.5 font-bold text-white disabled:opacity-60">{saving?"Saving...":"Save badge"}</button></div></form></div>}
 {deleting&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 text-center shadow-2xl"><h3 className="text-xl font-bold">Delete {deleting.name}?</h3><p className="mt-3 text-sm text-gray-500">This permanently removes the badge and removes it from all users who earned it.</p><div className="mt-6 flex justify-center gap-3"><button onClick={()=>setDeleting(null)} className="rounded-xl border px-5 py-2.5">Cancel</button><button disabled={saving} onClick={remove} className="rounded-xl bg-red-600 px-5 py-2.5 font-bold text-white">Delete badge</button></div></div></div>}
 </section>;
}
